#!/usr/bin/env python3
"""init_warpx/gen_heater_deck.py — render the 2D WarpX heater-driven piston deck.

Thin CLI over ``src/heater_spec.py`` (load / validate / freeze) and
``src/heater_deck.py`` (render / verify).  All the logic lives in ``src/`` so it is
covered by ``pytest --cov=src``; this file is argparse and file IO.

Why a text deck and not PICMI: ``ParticleHeater`` / ``TargetInjector`` are ParmParse-only
on the lab fork's ``feature/particle-heater`` branch.  No PICMI binding exists anywhere
under ``warpx/Python/``, and every pre-built ``pywarpx`` predates the operator commits,
so a PICMI driver would silently produce a physics-free run.

The mapping spec -> deck is one-way: edit the run spec and regenerate.  ``--check`` and
``--verify`` are the two directions of the closing loop — the first says the deck on disk
is still the spec's deck, the second says so of the ``warpx_used_inputs`` WarpX echoed
after the run.

Usage
-----
    conda activate analysis          # numpy + PyYAML only; no yt, no WarpX needed
    python init_warpx/gen_heater_deck.py --config runs/magshockz_2d_heater.warpx.yaml
    python init_warpx/gen_heater_deck.py --config ...yaml --smoke --no-heater
    python init_warpx/gen_heater_deck.py --config ...yaml --check    # writes nothing
    python init_warpx/gen_heater_deck.py --config ...yaml --verify   # post-run closure

Writes into ``input_files/warpx/<run_id>/`` (gitignored, regenerable):
    inputs_2d_heater           production deck
    inputs_2d_heater_smoke     quarter domain / 4 ppc / 200 steps  (--smoke)
    inputs_2d_heater_noheater  null control, heater block omitted  (--no-heater)
    run.yaml                   frozen resolved spec + derived values + provenance
    run_env.sh                 HEATER_EXE etc., sourced by run_heater_2d.sbatch
    scaling_report.txt         the printed report, kept with the deck
"""

from __future__ import annotations

import argparse
import hashlib
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

_HERE = Path(__file__).resolve().parent
_REPO = _HERE.parent
sys.path.insert(0, str(_REPO / "src"))

import heater_deck  # noqa: E402  (needs the sys.path above)
import heater_spec  # noqa: E402

DEFAULT_SPEC = _REPO / "runs" / "magshockz_2d_heater.warpx.yaml"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _git_provenance(repo: Path) -> dict[str, str]:
    """HEAD and dirty-file count for ``repo``, or placeholders when git is unavailable.

    Lives here rather than in ``src/`` so the pure layer stays subprocess-free.
    """
    def run(*args: str) -> str:
        try:
            return subprocess.run(("git", "-C", str(repo), *args), check=True,
                                  capture_output=True, text=True).stdout.strip()
        except (OSError, subprocess.CalledProcessError):
            return "n/a"

    dirty = run("status", "--porcelain")
    return {"git": run("rev-parse", "HEAD"),
            "dirty_files": str(len(dirty.splitlines())) if dirty != "n/a" else "n/a"}


def _run_env(spec: dict[str, Any]) -> str:
    """The ``runtime:`` block as shell exports the sbatch sources before its defaults.

    Every export defers to an already-set value, so the spec supplies a default without
    taking the variable over: ``HEATER_EXE=<cpu app> sbatch …`` — the documented CPU
    fallback — must still win over what the spec names.
    """
    runtime = spec.get("runtime") or {}
    return "\n".join([
        "# GENERATED by init_warpx/gen_heater_deck.py from the run spec's runtime: block.",
        "# run_heater_2d.sbatch sources this before applying its own ${VAR:-default}s, so",
        "# the spec chooses the binary without the sbatch's NERSC logic being forked into",
        "# a per-run copy. ${VAR:-...} here so an env var set on the sbatch command line",
        "# (the CPU-app fallback) still overrides the spec.",
        f"export HEATER_EXE=${{HEATER_EXE:-{runtime.get('exe', '')}}}",
        "",
    ])


def _write(path: Path, text: str, written: list[Path]) -> None:
    path.write_text(text)
    written.append(path)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Render the 2D WarpX heater-driven piston deck from a run spec.")
    parser.add_argument("--config", default=str(DEFAULT_SPEC),
                        help="heater_pic_2d run spec (default: %(default)s)")
    parser.add_argument("--smoke", action="store_true",
                        help="also write the reduced smoke deck")
    parser.add_argument("--no-heater", action="store_true",
                        help="also write the heater-off null control deck, identical in "
                             "every other respect — the controlled test for whether the "
                             "ambient <u^2> rise is numerical grid heating")
    parser.add_argument("--output-dir",
                        help="override input_files/warpx/<meta.run_id>/")
    parser.add_argument("--check", action="store_true",
                        help="verify the deck already on disk against the spec and exit; "
                             "writes nothing, so it is safe against a running job")
    parser.add_argument("--verify", action="store_true",
                        help="verify the post-run warpx_used_inputs against the spec "
                             "and exit; writes nothing")
    parser.add_argument("--quiet", action="store_true",
                        help="write the files without printing the report")
    args = parser.parse_args()

    spec_path = Path(args.config).resolve()
    spec = heater_spec.load(spec_path)
    scaling = heater_spec.scaling(spec, smoke=False)

    run_id = (spec.get("meta") or {}).get(
        "run_id", spec_path.name.replace(".warpx.yaml", "").replace(".yaml", ""))
    out_dir = (Path(args.output_dir) if args.output_dir
               else _REPO / "input_files" / "warpx" / run_id)
    deck_name = (spec.get("meta") or {}).get("deck", heater_deck.DECK_NAME)

    if args.check or args.verify:
        target = out_dir / ("warpx_used_inputs" if args.verify else deck_name)
        if not target.is_file():
            print(f"ERROR: {os.path.relpath(target, _REPO)} does not exist", file=sys.stderr)
            raise SystemExit(1)
        drift = heater_deck.verify(spec, scaling, target)
        label = os.path.relpath(target, _REPO)
        if drift:
            print(f"DRIFT: {label} no longer matches {spec_path.name}", file=sys.stderr)
            for warning in drift:
                print(f"  * {warning}", file=sys.stderr)
            raise SystemExit(1)
        print(f"verified: {label} resolves back to the spec")
        return

    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    deck_path = out_dir / deck_name
    _write(deck_path, heater_deck.render_deck(spec, scaling), written)
    if args.smoke:
        _write(out_dir / f"{deck_name}_smoke",
               heater_deck.render_deck(spec, heater_spec.scaling(spec, smoke=True),
                                       smoke=True), written)
    if args.no_heater:
        _write(out_dir / f"{deck_name}_noheater",
               heater_deck.render_deck(spec, scaling, no_heater=True), written)

    provenance = {
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "spec": str(spec_path),
        "spec_sha256": _sha256(spec_path),
        "deck_sha256": _sha256(deck_path),
        "magshockz": _git_provenance(_REPO),
        "python": sys.version.split()[0],
    }
    _write(out_dir / "run.yaml",
           yaml.safe_dump(heater_spec.freeze(spec, scaling, provenance=provenance),
                          sort_keys=False), written)
    _write(out_dir / "run_env.sh", _run_env(spec), written)

    report = heater_deck.scaling_report(
        spec, scaling,
        ppc_each_dim=tuple(int(v) for v in spec["scaling"]["ppc_each_dim"]),
        max_step=scaling.max_step)
    _write(out_dir / "scaling_report.txt", report + "\n", written)

    # Self-verify: parse the deck we just wrote, resolve its my_constants, and diff the
    # resulting numbers against the spec. Catches a block builder silently dropping a
    # line, which a visual read of an 11 KB deck will not.
    drift = heater_deck.verify(spec, scaling, deck_path)

    if not args.quiet:
        print(report)
        print()
    for path in written:
        print(f"Wrote -> {os.path.relpath(path, _REPO)}")

    runtime = spec.get("runtime") or {}
    if runtime.get("nodes") and runtime.get("walltime"):
        print(f"Launch:  sbatch -N {runtime['nodes']} -t {runtime['walltime']} "
              f"init_warpx/run_heater_2d.sbatch")

    if drift:
        print("DRIFT: the deck does NOT resolve back to the spec", file=sys.stderr)
        for warning in drift:
            print(f"  * {warning}", file=sys.stderr)
        raise SystemExit(1)
    print("verified: deck resolves back to the spec")

    for warning in heater_spec.validate(spec, scaling, out_dir=out_dir):
        print(f"WARNING: {warning}", file=sys.stderr)


if __name__ == "__main__":
    main()
