"""heater_piston_scaling.py — map a FLASH piston to a reduced-mass WarpX PIC deck.

The 2D WarpX runs generated by ``init_warpx/gen_heater_deck.py`` do not read FLASH
data.  They *grow* their piston: a dense cold slab is replenished by WarpX's
``TargetInjector`` and heated by ``ParticleHeater``'s momentum-space diffusion (the
PSC / Fox et al. 2018 laser-ablation surrogate), and the heated slab expands as a
self-consistent, kinetically smooth piston into a uniform magnetized ambient.

This module is the bridge: it takes the FLASH-measured piston and ambient state
(:class:`PistonTargets`, produced by ``scripts/flash_piston_profile.py``) and returns
the deck's constants (:class:`ReducedScaling`).

What can and cannot be matched
------------------------------
A full-PIC run of a real 7 T, ~1e24 m^-3, cm-scale, Z=13/14 experiment is not
affordable, so the deck deliberately runs at a reduced ion/electron mass ratio and an
arbitrary reference density.  That fixes *dimensionless* similarity, not absolute
scales.  Held fixed (:meth:`PistonTargets.invariants`):

  * ``M_A``   = v_piston / v_A                 — Alfvenic drive strength
  * ``M_ms``  = v_piston / sqrt(v_A^2 + c_s^2) — super-criticality
  * ``beta_e``, ``beta_i``                     — ambient pressure balance
  * ``n_piston / n_ambient``                   — piston/ambient contrast
  * ``r_spot / d_i``                           — piston transverse geometry
  * ``omega_ci * t_run``                       — gyroperiods simulated

Necessarily broken, and why it is acceptable:

  * ``m_i/m_e`` (1836*A/Z -> ``mass_ratio``).  Compresses the electron/ion scale
    separation so d_e is resolvable; standard practice in this regime.  Consequence:
    ``omega_pe/omega_ci`` and ``v_th,e/c`` are not the experiment's, so electron-scale
    kinetics (Weibel growth rates, electron heating rates) are only qualitative.
  * ``Z`` -> 1.  The heater/injector pair is charge-state agnostic; a single
    hydrogenic ion carries the inertia that sets d_i and the gyroradius.
  * absolute ns / um.  The run lives in ``1/omega_pe`` and ``d_e``;
    :meth:`ReducedScaling.to_ns` / :meth:`ReducedScaling.to_um` convert back through
    the matched ion scales, which is how ``scripts/warpx_heater_compare.py`` puts the
    two codes on one axis.

Stdlib + numpy only, so this is unit-tested in CI alongside the rest of ``src/`` (no
yt, no WarpX, no astropy).  SI throughout; every dimensionful name carries its unit.
"""

from dataclasses import dataclass, field
from typing import Sequence

import numpy as np

C_LIGHT_MS = 2.99792458e8
MU_0 = 4.0e-7 * np.pi
EPSILON_0 = 1.0 / (MU_0 * C_LIGHT_MS**2)
Q_E = 1.602176634e-19
M_E_KG = 9.1093837015e-31
M_P_KG = 1.67262192369e-27

GAMMA_DEFAULT = 5.0 / 3.0

#: ``v_piston = KAPPA_DEFAULT * c_s(theta_e)`` — the expansion-front speed of a heated
#: slab in units of its own ion-acoustic speed.
#:
#: MEASURED, not assumed.  The first 2D run (568x2832, theta_e = 0.04, mass_ratio 100)
#: aimed for 0.050 c and delivered 0.0202 c, i.e. kappa = 1.01 — so the front speed and
#: every quantity derived through it (B0, the ambient temperatures, M_A) were off by 2.5x.
#: The earlier 2.5 came from the classic rarefaction-front result and from reading the
#: validated 1D run's *shock* speed (0.074 c) as if it were the piston contact speed; in
#: 2D, with a finite heating spot, the contact moves at about one c_s.
KAPPA_DEFAULT = 1.01

#: Reference point for :meth:`ReducedScaling.cost_report`: the validated
#: ``heating_operator/run_prod_compare/L0_launch`` job did 2048x4096 cells for 15000
#: steps at 16 macroparticles/cell over 2 domain-filling species pairs, on 4
#: Perlmutter CPU nodes (64 ranks) in 2 h 55 m.
_COST_REF_WORK = (2048.0 * 4096.0) * 16.0 * 2.0 * 15000.0
_COST_REF_NODE_HOURS = 4.0 * (2.0 + 55.0 / 60.0)

#: AMReX blocking factor the cell counts are rounded up to.
BLOCKING_DEFAULT = 8

#: Below this ``lambda_De / dx`` the cold ambient is at risk of numerical (grid) heating.
#: From the OSIRIS dx/ppc convergence scan recorded in CLAUDE.md: the Debye length does
#: NOT have to be resolved, but runs below ~0.03 heated away while 0.1 and 0.3 stayed
#: clean over several gyroperiods.  A cold, low-beta upstream is exactly the case that
#: pushes a heater deck under it, so :func:`derive` checks and warns.
DEBYE_PER_CELL_MIN = 0.03

#: Piston-electron thermal speed (in c) above which the heater's non-relativistic momentum
#: kicks stop reproducing the ``theta_e`` they are meant to impose.  gamma = 1.05 at 0.3.
RELATIVISTIC_VTH_MAX = 0.3

#: Plotfile count a production run should land in.  Below ~10 frames the front trajectory
#: cannot be fitted; above ~200 the I/O throttles the run harder than the physics does
#: (measured: 4.6 GB per dump with raw particles against 0.27 GB of grid fields).  The
#: cadence is set in STEPS, so it has to be rescaled whenever the step count moves —
#: which is what ``heater_spec.validate`` uses this to catch.
PLOTFILE_COUNT_RANGE = (10, 200)


# ---------------------------------------------------------------------------
# Elementary SI plasma quantities
# ---------------------------------------------------------------------------

def plasma_frequency_rad_s(electron_density_per_m3: float) -> float:
    """Electron plasma frequency omega_pe = sqrt(n_e e^2 / (eps0 m_e)) [rad/s]."""
    if electron_density_per_m3 <= 0.0:
        return float("nan")
    return float(np.sqrt(electron_density_per_m3 * Q_E**2 / (EPSILON_0 * M_E_KG)))


def electron_skin_depth_m(electron_density_per_m3: float) -> float:
    """Electron inertial length d_e = c / omega_pe [m]."""
    omega_pe = plasma_frequency_rad_s(electron_density_per_m3)
    if not (np.isfinite(omega_pe) and omega_pe > 0.0):
        return float("nan")
    return float(C_LIGHT_MS / omega_pe)


def alfven_speed_ms(b_tesla: float, ion_density_per_m3: float,
                    ion_mass_kg: float) -> float:
    """Alfven speed v_A = B / sqrt(mu0 n_i m_i) [m/s]."""
    if ion_density_per_m3 <= 0.0 or ion_mass_kg <= 0.0:
        return float("nan")
    return float(abs(b_tesla) / np.sqrt(MU_0 * ion_density_per_m3 * ion_mass_kg))


def ion_acoustic_speed_ms(
    te_ev: float,
    ti_ev: float,
    ion_mass_kg: float,
    charge_state: float = 1.0,
    gamma_electron: float = 1.0,
    gamma_ion: float = GAMMA_DEFAULT,
) -> float:
    """Ion-acoustic speed c_s = sqrt((g_e Z kT_e + g_i kT_i)/m_i) [m/s].

    ``gamma_electron = 1`` (isothermal electrons) is the usual choice for an expanding
    laser plasma; ``gamma_ion = 5/3`` for adiabatic ions.  Negative temperatures are
    clamped to zero so a noisy FLASH cell cannot produce a nan.
    """
    if ion_mass_kg <= 0.0:
        return float("nan")
    pressure_term = (gamma_electron * charge_state * max(te_ev, 0.0)
                     + gamma_ion * max(ti_ev, 0.0)) * Q_E
    return float(np.sqrt(pressure_term / ion_mass_kg))


def ion_inertial_length_m(ion_density_per_m3: float, ion_mass_kg: float,
                          charge_state: float = 1.0) -> float:
    """Ion inertial length d_i = c / omega_pi [m]."""
    if ion_density_per_m3 <= 0.0 or ion_mass_kg <= 0.0:
        return float("nan")
    omega_pi = np.sqrt(ion_density_per_m3 * (charge_state * Q_E) ** 2
                       / (EPSILON_0 * ion_mass_kg))
    return float(C_LIGHT_MS / omega_pi)


def ion_gyrofrequency_rad_s(b_tesla: float, ion_mass_kg: float,
                            charge_state: float = 1.0) -> float:
    """Ion cyclotron frequency omega_ci = Z e |B| / m_i [rad/s]."""
    if ion_mass_kg <= 0.0:
        return float("nan")
    return float(charge_state * Q_E * abs(b_tesla) / ion_mass_kg)


def plasma_beta(number_density_per_m3: float, temperature_ev: float,
                b_tesla: float) -> float:
    """Single-species beta = n kT / (B^2 / 2 mu0) [dimensionless]."""
    if b_tesla == 0.0:
        return float("inf")
    magnetic_pressure_pa = b_tesla * b_tesla / (2.0 * MU_0)
    return float(number_density_per_m3 * temperature_ev * Q_E / magnetic_pressure_pa)


def theta_from_ev(temperature_ev: float, mass_kg: float) -> float:
    """Dimensionless temperature theta = kT / (m c^2), i.e. WarpX's ``u_std**2``."""
    return float(temperature_ev * Q_E / (mass_kg * C_LIGHT_MS**2))


def ev_from_theta(theta: float, mass_kg: float) -> float:
    """Inverse of :func:`theta_from_ev`."""
    return float(theta * mass_kg * C_LIGHT_MS**2 / Q_E)


def _safe_ratio(numerator: float, denominator: float) -> float:
    """``numerator/denominator``, returning +-inf rather than raising when it is 0.

    An unmagnetized target (B = 0) gives v_A = 0 and so an infinite Mach number;
    :func:`derive` rejects that with a message about the field, which is far more
    useful than a ZeroDivisionError from deep inside a property.
    """
    if denominator == 0.0:
        return float("inf") if numerator >= 0.0 else float("-inf")
    return float(numerator / denominator)


def cfl_timestep_s(cell_size_m: float, cfl: float, n_dims: int) -> float:
    """Yee-solver CFL step for a square cell: dt = cfl * dx / (c sqrt(n_dims)) [s].

    Reproduces both decks whose dt is printed: 1D dx = 0.5 d_e at cfl 0.75 gives
    dt*omega_pe = 0.375, and 2D dx = 1 d_e at cfl 0.75 gives 0.5303.
    """
    return float(cfl * cell_size_m / (C_LIGHT_MS * np.sqrt(n_dims)))


# ---------------------------------------------------------------------------
# The FLASH-measured target
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class PistonTargets:
    """FLASH-measured piston + ambient state, as written by
    ``scripts/flash_piston_profile.py`` and recorded in the run spec's
    ``flash_target:`` block.

    The ambient quantities are taken *just ahead of the piston front*, not at the
    FLASH initial condition: the chamber plasma rarefies substantially over the first
    few ns, and it is the state the piston actually drives into that sets M_A and
    beta.  Same "self-consistent dump" discipline the OSIRIS side follows.
    """

    n_amb_per_m3: float
    b_amb_tesla: float
    te_amb_ev: float
    ti_amb_ev: float
    n_piston_drive_per_m3: float
    """Piston electron density just BEHIND the front — the density that drives the
    shock.  Deliberately not the profile's global peak: on these line-outs that peak
    sits in the dense stagnated material next to the target, ~40x above the material
    actually arriving at the front, and using it overstates the contrast accordingly."""
    v_front_ms: float
    l_piston_m: float
    """Piston density e-folding length into the upstream."""
    r_spot_m: float
    """Piston transverse half-width, i.e. the laser-spot scale."""
    t_window_s: float
    """Duration of FLASH evolution the deck should reproduce."""
    a_amb: float = 26.98
    """Ambient ion mass number (Al foam chamber)."""
    z_amb: float = 13.0
    a_piston: float = 28.0855
    """Piston ion mass number (Si target)."""
    z_piston: float = 14.0
    gamma: float = GAMMA_DEFAULT
    source: str = ""
    """Provenance string, echoed into the generated deck's header."""

    @property
    def m_i_amb_kg(self) -> float:
        return self.a_amb * M_P_KG

    @property
    def n_i_amb_per_m3(self) -> float:
        """Ambient ion density, from quasineutrality n_e = Z n_i."""
        return self.n_amb_per_m3 / self.z_amb

    @property
    def v_alfven_ms(self) -> float:
        return alfven_speed_ms(self.b_amb_tesla, self.n_i_amb_per_m3, self.m_i_amb_kg)

    @property
    def c_s_ms(self) -> float:
        """Ambient ion-acoustic speed."""
        return ion_acoustic_speed_ms(self.te_amb_ev, self.ti_amb_ev, self.m_i_amb_kg,
                                     charge_state=self.z_amb, gamma_ion=self.gamma)

    @property
    def v_fast_ms(self) -> float:
        """Ambient fast-magnetosonic speed sqrt(v_A^2 + c_s^2)."""
        return float(np.hypot(self.v_alfven_ms, self.c_s_ms))

    @property
    def mach_alfven(self) -> float:
        return _safe_ratio(self.v_front_ms, self.v_alfven_ms)

    @property
    def mach_magnetosonic(self) -> float:
        return _safe_ratio(self.v_front_ms, self.v_fast_ms)

    @property
    def beta_e(self) -> float:
        return plasma_beta(self.n_amb_per_m3, self.te_amb_ev, self.b_amb_tesla)

    @property
    def beta_i(self) -> float:
        return plasma_beta(self.n_i_amb_per_m3, self.ti_amb_ev, self.b_amb_tesla)

    @property
    def contrast(self) -> float:
        """Piston/ambient electron-density contrast."""
        return float(self.n_piston_drive_per_m3 / self.n_amb_per_m3)

    @property
    def d_i_m(self) -> float:
        return ion_inertial_length_m(self.n_i_amb_per_m3, self.m_i_amb_kg,
                                     charge_state=self.z_amb)

    @property
    def omega_ci_rad_s(self) -> float:
        return ion_gyrofrequency_rad_s(self.b_amb_tesla, self.m_i_amb_kg,
                                       charge_state=self.z_amb)

    @property
    def gyroperiod_s(self) -> float:
        omega_ci = self.omega_ci_rad_s
        if not (np.isfinite(omega_ci) and omega_ci > 0.0):
            return float("nan")
        return float(2.0 * np.pi / omega_ci)

    @property
    def l_piston_di(self) -> float:
        return float(self.l_piston_m / self.d_i_m)

    @property
    def r_spot_di(self) -> float:
        return float(self.r_spot_m / self.d_i_m)

    @property
    def t_window_gyro(self) -> float:
        """Requested FLASH window in ambient ion gyroperiods."""
        return float(self.t_window_s / self.gyroperiod_s)

    def invariants(self) -> dict[str, float]:
        """The dimensionless numbers the reduced-mass deck is built to preserve."""
        return {
            "M_A": self.mach_alfven,
            "M_ms": self.mach_magnetosonic,
            "beta_e": self.beta_e,
            "beta_i": self.beta_i,
            "contrast": self.contrast,
            "r_spot/d_i": self.r_spot_di,
            "t_run/T_ci": self.t_window_gyro,
        }


# ---------------------------------------------------------------------------
# The reduced-mass deck
# ---------------------------------------------------------------------------

@dataclass
class ReducedScaling:
    """Constants for the 2D WarpX heater deck, plus its own dimensionless numbers.

    Lengths appear both in metres and in ``d_e``, because the deck writes them in
    skin depths (``-768.*de``) while the physics is set in SI, and the two must agree.
    """

    n0_per_m3: float
    """Ambient electron density of the simulation; sets d_e and 1/omega_pe."""
    mass_ratio: float
    omega_pe_rad_s: float
    d_e_m: float
    d_i_m: float
    m_i_kg: float

    theta_e_heater: float
    """Heater aim temperature kT_e/(m_e c^2), the ``foil.<species>.theta`` input."""
    v_piston_ms: float
    v_piston_c: float
    c_s_piston_ms: float
    kappa: float

    n_target_per_m3: float
    """Piston (target) density the injector relaxes towards."""
    n_amb_per_m3: float
    b0_tesla: float
    """Uniform out-of-plane field."""
    v_alfven_ms: float
    te_amb_ev: float
    ti_amb_ev: float
    theta_e_amb: float
    theta_i_amb: float
    theta_e_cold: float
    """Piston initial (pre-heating) electron temperature; the heater sets the rest."""
    theta_i_cold: float

    cell_size_de: float
    slab_halfwidth_de: float
    spot_radius_de: float
    domain_x_halfwidth_de: float
    domain_z_halfwidth_de: float
    n_cells_x: int
    n_cells_z: int

    dt_s: float
    dt_omega_pe: float
    t_run_s: float
    max_step: int
    gyroperiod_s: float
    t_run_gyro: float

    v_flow_ms: float = 0.0
    u_flow: float = 0.0
    """gamma*beta of the bulk drift — what the deck writes as ``ux_mean``."""
    e_motional_v_per_m: float = 0.0
    """Ez = -v_flow * B0, the field that makes the drift an exact equilibrium."""

    warnings: list[str] = field(default_factory=list)
    targets: PistonTargets | None = None

    @property
    def mach_alfven(self) -> float:
        return float(self.v_piston_ms / self.v_alfven_ms)

    @property
    def c_s_amb_ms(self) -> float:
        """Ambient ion-acoustic speed in the sim (Z = 1)."""
        return ion_acoustic_speed_ms(self.te_amb_ev, self.ti_amb_ev, self.m_i_kg)

    @property
    def mach_magnetosonic(self) -> float:
        return float(self.v_piston_ms / np.hypot(self.v_alfven_ms, self.c_s_amb_ms))

    @property
    def beta_e(self) -> float:
        return plasma_beta(self.n0_per_m3, self.te_amb_ev, self.b0_tesla)

    @property
    def beta_i(self) -> float:
        return plasma_beta(self.n0_per_m3, self.ti_amb_ev, self.b0_tesla)

    @property
    def contrast(self) -> float:
        return float(self.n_target_per_m3 / self.n_amb_per_m3)

    @property
    def debye_length_de(self) -> float:
        """Ambient electron Debye length in electron skin depths.

        ``lambda_De = v_th,e/omega_pe = sqrt(theta_e) * d_e``, so this is just
        ``sqrt(theta_e_amb)``.
        """
        return float(np.sqrt(self.theta_e_amb))

    @property
    def debye_per_cell(self) -> float:
        """``lambda_De / dx`` — the numerical-heating margin; see :data:`DEBYE_PER_CELL_MIN`."""
        return float(self.debye_length_de / self.cell_size_de)

    @property
    def slab_halfwidth_di(self) -> float:
        return float(self.slab_halfwidth_de * self.d_e_m / self.d_i_m)

    @property
    def r_spot_di(self) -> float:
        return float(self.spot_radius_de * self.d_e_m / self.d_i_m)

    @property
    def steps_per_gyroperiod(self) -> float:
        """Timesteps per ambient ion gyroperiod — the run's own clock.

        Drive windows and run lengths are specified in ``T_ci`` rather than in steps so
        they survive changes to ``cell_size_de`` and ``cfl``; this is the conversion.
        """
        return float(self.gyroperiod_s / self.dt_s)

    @property
    def cell_size_de_actual(self) -> float:
        """The dx the deck actually gets, after rounding the cell count to ``blocking``.

        ``n_cells_x`` is rounded UP to the blocking factor while the domain halfwidth is
        not, so the delivered cell is slightly smaller than the requested one — and it is
        this value, not the request, that sets WarpX's ``dt`` and hence how much physical
        time ``max_step`` buys.
        """
        return float(2.0 * self.domain_x_halfwidth_de / self.n_cells_x)

    def invariants(self) -> dict[str, float]:
        return {
            "M_A": self.mach_alfven,
            "M_ms": self.mach_magnetosonic,
            "beta_e": self.beta_e,
            "beta_i": self.beta_i,
            "contrast": self.contrast,
            "r_spot/d_i": self.r_spot_di,
            "t_run/T_ci": self.t_run_gyro,
        }

    def to_ns(self, t_omega_pe: np.ndarray | float) -> np.ndarray:
        """Sim time [1/omega_pe] -> FLASH-equivalent time [ns].

        The bridge is the ion gyroperiod, the slowest matched scale: one sim T_ci is
        one FLASH T_ci.  Converting through 1/omega_pe instead would be wrong by the
        deliberately broken mass ratio.
        """
        if self.targets is None:
            raise ValueError("to_ns needs the FLASH targets; build with derive(...)")
        t_gyro = np.asarray(t_omega_pe, dtype=float) / (self.omega_pe_rad_s
                                                        * self.gyroperiod_s)
        return t_gyro * self.targets.gyroperiod_s * 1e9

    def to_um(self, x_de: np.ndarray | float) -> np.ndarray:
        """Sim length [d_e] -> FLASH-equivalent length [um], bridged through d_i."""
        if self.targets is None:
            raise ValueError("to_um needs the FLASH targets; build with derive(...)")
        x_di = np.asarray(x_de, dtype=float) * self.d_e_m / self.d_i_m
        return x_di * self.targets.d_i_m * 1e6

    def cost_report(self, ppc_each_dim: Sequence[int] = (5, 5),
                    n_species: int = 4) -> dict[str, float]:
        """Rough cell / macroparticle / node-hour estimate.

        Node-hours scale linearly in (macroparticles x steps) from the one measured
        point we have (see ``_COST_REF_WORK``).  That is the right leading order for
        PIC but ignores the field solve, load imbalance and the growing injected
        inventory — a factor-of-two estimate, not a reservation.
        """
        ppc = int(ppc_each_dim[0]) * int(ppc_each_dim[1])
        cells = float(self.n_cells_x) * float(self.n_cells_z)
        macroparticles = cells * ppc * n_species
        return {
            "cells": cells,
            "ppc_per_species": float(ppc),
            "macroparticles": macroparticles,
            "steps": float(self.max_step),
            "node_hours": (_COST_REF_NODE_HOURS * macroparticles * self.max_step
                           / _COST_REF_WORK),
        }


def derive(
    targets: PistonTargets,
    n0_per_m3: float,
    mass_ratio: float = 100.0,
    *,
    v_piston_c: float = 0.05,
    kappa: float = KAPPA_DEFAULT,
    theta_e_heater: float | None = None,
    cell_size_de: float = 0.5,
    slab_halfwidth_di: float = 2.0,
    domain_x_halfwidth_de: float | None = None,
    domain_z_halfwidth_de: float | None = None,
    z_margin: float = 1.35,
    cfl: float = 0.75,
    theta_e_cold: float = 1.0e-3,
    run_window_gyro: float | None = None,
    v_flow_ms: float = 0.0,
    blocking: int = BLOCKING_DEFAULT,
) -> ReducedScaling:
    """Turn FLASH-measured targets into the 2D heater deck's constants.

    Parameters
    ----------
    targets :
        The FLASH measurement.
    n0_per_m3 :
        Ambient electron density of the *simulation*.  Free: it only sets the ``d_e``
        / ``1/omega_pe`` the deck is expressed in and cancels out of every matched
        invariant.  1e18 keeps the numbers close to the validated 1D shock run.
    mass_ratio :
        ``m_i/m_e`` in the sim.  100 is the Fox-2018 / PSC value.
    v_piston_c :
        Target expansion-front speed in units of c — the run's *speed budget*.  Larger
        means fewer steps to cross the domain but a less physical, mildly relativistic
        electron population.  ``theta_e_heater`` follows from it.
    kappa :
        ``v_piston / c_s(theta_e)``; see :data:`KAPPA_DEFAULT`.
    theta_e_heater :
        Override the heater aim temperature directly — the hand-tuning knob.
        ``v_piston`` is then recomputed from it and ``b0_tesla`` moves to hold ``M_A``,
        which is the behaviour the tuning loop wants.
    cell_size_de :
        Square cell size in electron skin depths.
    slab_halfwidth_di :
        Heater/injector slab half-width in ion inertial lengths.  This is the piston
        *reservoir*, the analogue of FLASH's ablator; it is not directly
        FLASH-measurable, and 1-2 d_i is the PSC flatfoil value.
    domain_x_halfwidth_de, domain_z_halfwidth_de :
        ``None`` sizes them from the physics: x from the heating spot (4 spot radii, so
        the spot's periodic images stay clear of it), z from how far the front travels
        in ``t_run`` times ``z_margin`` — the slab is symmetric about z = 0, so *both*
        fronts must stay inside the periodic box.
    run_window_gyro :
        Duration in ambient ion gyroperiods; ``None`` uses the FLASH window.
    v_flow_ms :
        Uniform bulk drift along x, applied to *every* species together with the
        motional ``Ez = -v_flow B0`` so the initial state is an exact equilibrium.
        That makes it a Galilean boost: the shock structure is unchanged, just
        advected.  ``TargetInjector`` has no drift knob, so with a non-zero flow the
        continuously injected piston particles enter at rest in the boosted frame and
        gyrate; a warning says so.  Keep it 0 for physics runs and use it for the
        frame-consistency test.
    """
    if n0_per_m3 <= 0.0:
        raise ValueError(f"n0_per_m3 must be positive, got {n0_per_m3!r}")
    if mass_ratio <= 0.0:
        raise ValueError(f"mass_ratio must be positive, got {mass_ratio!r}")
    if kappa <= 0.0:
        raise ValueError(f"kappa must be positive, got {kappa!r}")

    warnings: list[str] = []

    omega_pe = plasma_frequency_rad_s(n0_per_m3)
    d_e_m = C_LIGHT_MS / omega_pe
    m_i_kg = mass_ratio * M_E_KG
    d_i_m = d_e_m * np.sqrt(mass_ratio)          # Z = 1, so n_i = n_e = n0

    theta_e_heater, v_piston_c = _resolve_drive(theta_e_heater, v_piston_c,
                                               kappa, mass_ratio)
    c_s_piston_ms = np.sqrt(theta_e_heater / mass_ratio) * C_LIGHT_MS
    v_piston_ms = kappa * c_s_piston_ms
    # The heater kicks u = gamma*v with no gamma factors (PSC convention), so what breaks
    # the theta_e <-> c_s relation is the ELECTRON thermal speed, not the piston speed --
    # and they differ by sqrt(mass_ratio)/kappa, a factor of 10 at mass_ratio 100. Guarding
    # on v_piston_c alone stayed silent at v_th,e = 0.5 c, which is where correcting kappa
    # to its measured 1.01 at v_piston_c = 0.05 lands.
    v_thermal_e_c = np.sqrt(theta_e_heater)
    if v_thermal_e_c > RELATIVISTIC_VTH_MAX:
        warnings.append(
            f"heater theta_e = {theta_e_heater:.3f} puts the piston electrons at "
            f"v_th/c = {v_thermal_e_c:.2f} (gamma = "
            f"{1.0 / np.sqrt(1.0 - min(v_thermal_e_c ** 2, 0.99)):.2f}), above "
            f"{RELATIVISTIC_VTH_MAX}: the heater's non-relativistic kicks make the "
            f"theta_e <-> c_s mapping unreliable. Lower v_piston_c or mass_ratio "
            f"(theta_e = mass_ratio*(v_piston_c/kappa)^2).")
    if v_piston_c > 0.2:
        warnings.append(
            f"piston speed {v_piston_c:.2f} c is mildly relativistic; prefer "
            f"v_piston_c <~ 0.1.")

    mach_alfven = targets.mach_alfven
    if not (np.isfinite(mach_alfven) and mach_alfven > 0.0):
        raise ValueError(
            f"FLASH targets give a non-finite Alfven Mach number ({mach_alfven!r}); "
            f"check n_amb_per_m3 / b_amb_tesla / v_front_ms.")
    v_alfven_ms = v_piston_ms / mach_alfven
    b0_tesla = v_alfven_ms * np.sqrt(MU_0 * n0_per_m3 * m_i_kg)

    # beta = n kT / (B^2/2mu0)  =>  T = beta B^2 / (2 mu0 n e)
    magnetic_pressure_pa = b0_tesla * b0_tesla / (2.0 * MU_0)
    te_amb_ev = targets.beta_e * magnetic_pressure_pa / (n0_per_m3 * Q_E)
    ti_amb_ev = targets.beta_i * magnetic_pressure_pa / (n0_per_m3 * Q_E)

    n_target_per_m3 = targets.contrast * n0_per_m3
    if targets.contrast <= 1.0:
        warnings.append(
            f"piston/ambient contrast is {targets.contrast:.2f} <= 1 — the 'piston' is "
            f"not denser than the ambient; check n_piston_drive_per_m3 vs n_amb_per_m3.")

    slab_halfwidth_de = slab_halfwidth_di * np.sqrt(mass_ratio)
    spot_radius_de = targets.r_spot_di * np.sqrt(mass_ratio)

    gyroperiod_s = 2.0 * np.pi * m_i_kg / (Q_E * b0_tesla)
    t_run_gyro = (targets.t_window_gyro if run_window_gyro is None
                  else float(run_window_gyro))
    t_run_s = t_run_gyro * gyroperiod_s

    dt_s = cfl_timestep_s(cell_size_de * d_e_m, cfl, n_dims=2)
    max_step = int(np.ceil(t_run_s / dt_s))

    z_needed_de = z_margin * (slab_halfwidth_de + v_piston_ms * t_run_s / d_e_m)
    if domain_z_halfwidth_de is None:
        domain_z_halfwidth_de = z_needed_de
    elif domain_z_halfwidth_de < z_needed_de:
        warnings.append(
            f"domain_z_halfwidth_de={domain_z_halfwidth_de:.0f} is below the "
            f"{z_needed_de:.0f} d_e the front needs over {t_run_gyro:.2f} T_ci — it "
            f"will wrap through the periodic boundary. Grow the domain or shorten "
            f"run_window_gyro.")

    if domain_x_halfwidth_de is None:
        domain_x_halfwidth_de = max(4.0 * spot_radius_de, 32.0)
    elif spot_radius_de > 0.0 and domain_x_halfwidth_de < 2.0 * spot_radius_de:
        warnings.append(
            f"domain_x_halfwidth_de={domain_x_halfwidth_de:.0f} is under 2 spot radii "
            f"({2 * spot_radius_de:.0f} d_e): the heater's periodic spot images overlap "
            f"the spot, so the heating is effectively uniform in x.")

    # A cold, low-beta upstream (which is what the unperturbed FLASH background is) makes
    # lambda_De small in cell units, and a full-PIC run that under-resolves it heats the
    # ambient numerically — indistinguishable from shock heating in the diagnostics unless
    # you are watching for it. Halving cell_size_de is the cheap fix.
    debye_per_cell = np.sqrt(theta_from_ev(te_amb_ev, M_E_KG)) / cell_size_de
    if debye_per_cell < DEBYE_PER_CELL_MIN:
        # Floored, not rounded, to the precision it is printed at: the exact value sits
        # ON the threshold, so a printed 0.827 that rounded UP from 0.8267 lands at
        # lambda_De/dx = 0.029997 and does not actually clear the bar it is offered for.
        suggested = np.floor(1e3 * cell_size_de * debye_per_cell
                             / DEBYE_PER_CELL_MIN) / 1e3
        warnings.append(
            f"lambda_De/dx = {debye_per_cell:.4f} is below {DEBYE_PER_CELL_MIN} — the "
            f"cold ambient (T_e = {te_amb_ev:.1f} eV) is at risk of numerical grid "
            f"heating over {t_run_gyro:.3f} T_ci. Halve cell_size_de (to "
            f"{suggested:.3f} or less), raise "
            f"particle_shape, or raise ppc — and watch the ambient <u^2> history either "
            f"way.")

    beta_flow = v_flow_ms / C_LIGHT_MS
    if abs(beta_flow) >= 1.0:
        raise ValueError(f"v_flow_ms={v_flow_ms:g} is not sub-luminal")
    u_flow = beta_flow / np.sqrt(1.0 - beta_flow**2)
    if v_flow_ms != 0.0:
        warnings.append(
            "v_flow_ms != 0: all species drift and Ez = -v_flow*B0 is imposed, so this "
            "is an exact equilibrium but a pure Galilean boost. TargetInjector has no "
            "u_mean knob, so injected piston particles enter at rest in this frame and "
            "gyrate at rho = v_flow/omega_ci — use short frame-check runs only.")

    return ReducedScaling(
        n0_per_m3=float(n0_per_m3),
        mass_ratio=float(mass_ratio),
        omega_pe_rad_s=float(omega_pe),
        d_e_m=float(d_e_m),
        d_i_m=float(d_i_m),
        m_i_kg=float(m_i_kg),
        theta_e_heater=float(theta_e_heater),
        v_piston_ms=float(v_piston_ms),
        v_piston_c=float(v_piston_c),
        c_s_piston_ms=float(c_s_piston_ms),
        kappa=float(kappa),
        n_target_per_m3=float(n_target_per_m3),
        n_amb_per_m3=float(n0_per_m3),
        b0_tesla=float(b0_tesla),
        v_alfven_ms=float(v_alfven_ms),
        te_amb_ev=float(te_amb_ev),
        ti_amb_ev=float(ti_amb_ev),
        theta_e_amb=theta_from_ev(te_amb_ev, M_E_KG),
        theta_i_amb=theta_from_ev(ti_amb_ev, m_i_kg),
        theta_e_cold=float(theta_e_cold),
        # Cold ions at the same physical temperature as the cold electrons.
        theta_i_cold=float(theta_e_cold / mass_ratio),
        cell_size_de=float(cell_size_de),
        slab_halfwidth_de=float(slab_halfwidth_de),
        spot_radius_de=float(spot_radius_de),
        domain_x_halfwidth_de=float(domain_x_halfwidth_de),
        domain_z_halfwidth_de=float(domain_z_halfwidth_de),
        n_cells_x=_cell_count(2.0 * domain_x_halfwidth_de, cell_size_de, blocking),
        n_cells_z=_cell_count(2.0 * domain_z_halfwidth_de, cell_size_de, blocking),
        dt_s=float(dt_s),
        dt_omega_pe=float(dt_s * omega_pe),
        t_run_s=float(t_run_s),
        max_step=max_step,
        gyroperiod_s=float(gyroperiod_s),
        t_run_gyro=float(t_run_gyro),
        v_flow_ms=float(v_flow_ms),
        u_flow=float(u_flow),
        e_motional_v_per_m=float(-v_flow_ms * b0_tesla),
        warnings=warnings,
        targets=targets,
    )


def _resolve_drive(theta_e_heater: float | None, v_piston_c: float,
                   kappa: float, mass_ratio: float) -> tuple[float, float]:
    """Close the ``theta_e <-> v_piston`` pair, whichever one was given.

    ``c_s = sqrt(theta_e / (m_i/m_e)) c`` with isothermal electrons and cold ions, and
    ``v_piston = kappa c_s``, so the two are inverses of each other.
    """
    if theta_e_heater is None:
        if not 0.0 < v_piston_c < 1.0:
            raise ValueError(f"v_piston_c must be in (0, 1), got {v_piston_c!r}")
        return mass_ratio * (v_piston_c / kappa) ** 2, float(v_piston_c)

    if theta_e_heater <= 0.0:
        raise ValueError(f"theta_e_heater must be positive, got {theta_e_heater!r}")
    implied_v_piston_c = kappa * np.sqrt(theta_e_heater / mass_ratio)
    if implied_v_piston_c >= 1.0:
        raise ValueError(
            f"theta_e_heater={theta_e_heater:g} at mass_ratio={mass_ratio:g} implies a "
            f"piston speed {implied_v_piston_c:.2f} c — unphysical; lower theta_e.")
    return float(theta_e_heater), float(implied_v_piston_c)


def _cell_count(extent_de: float, cell_size_de: float, blocking: int) -> int:
    """Cells spanning ``extent_de``, rounded up to AMReX's blocking factor."""
    n = int(np.ceil(extent_de / cell_size_de))
    if blocking > 1:
        n = int(np.ceil(n / blocking) * blocking)
    return max(n, blocking)


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

def invariance_report(scaling: ReducedScaling, rel_tol: float = 1e-6) -> str:
    """A FLASH-vs-deck table of the matched invariants and the broken ones.

    ``rel_tol`` only controls the OK/OFF marker; the numbers are always printed, so a
    mismatch stays visible even when it is intentional (a hand-tuned theta_e that
    moves M_A, say).
    """
    targets = scaling.targets
    if targets is None:
        raise ValueError("invariance_report needs the FLASH targets")

    want, got = targets.invariants(), scaling.invariants()
    lines = ["Matched dimensionless invariants (FLASH -> deck)",
             f"  {'quantity':<18} {'FLASH':>12} {'deck':>12}  {'rel err':>9}"]
    for key, flash_value in want.items():
        deck_value = got[key]
        rel_err = (abs(deck_value - flash_value) / abs(flash_value)
                   if flash_value != 0.0 and np.isfinite(flash_value) else float("nan"))
        mark = "" if not np.isfinite(rel_err) or rel_err <= rel_tol else "   <-- OFF"
        lines.append(f"  {key:<18} {flash_value:>12.4g} {deck_value:>12.4g}  "
                     f"{rel_err:>9.2e}{mark}")

    flash_mass_ratio = targets.a_amb * M_P_KG / M_E_KG
    flash_wpe_over_wci = plasma_frequency_rad_s(targets.n_amb_per_m3) / targets.omega_ci_rad_s
    deck_wpe_over_wci = scaling.omega_pe_rad_s * scaling.gyroperiod_s / (2.0 * np.pi)
    rows = [
        ("m_i/m_e", flash_mass_ratio, scaling.mass_ratio),
        ("Z_ambient", targets.z_amb, 1.0),
        ("omega_pe/omega_ci", flash_wpe_over_wci, deck_wpe_over_wci),
        ("v_piston/c", targets.v_front_ms / C_LIGHT_MS, scaling.v_piston_c),
        ("n_ambient [m^-3]", targets.n_amb_per_m3, scaling.n0_per_m3),
        ("B_ambient [T]", targets.b_amb_tesla, scaling.b0_tesla),
        ("d_i [m]", targets.d_i_m, scaling.d_i_m),
        ("T_ci [s]", targets.gyroperiod_s, scaling.gyroperiod_s),
        # The slab is the piston reservoir, not the measured e-folding length; the deck
        # cannot and does not claim to reproduce the latter.
        ("L_piston/d_i", targets.l_piston_di, scaling.slab_halfwidth_di),
    ]
    lines += ["",
              "Deliberately NOT matched (reduced-mass PIC; see the module docstring)",
              f"  {'quantity':<18} {'FLASH':>12} {'deck':>12}"]
    lines += [f"  {name:<18} {flash_value:>12.4g} {deck_value:>12.4g}"
              for name, flash_value, deck_value in rows]
    return "\n".join(lines)
